name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /tmp
            rm -rf devops-aws-assignment
            git clone https://github.com/nikunjdaa-sit/devops-aws-assignment.git
            sudo cp devops-aws-assignment/index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html
            sudo systemctl reload nginx
            echo "Deployment successful!"
